---
- name: PHP | Update apt
  apt: update_cache=yes

- name: PHP | Install php7.0
  apt: pkg=php7.0 state=latest

- name: PHP | Install PHP Packages
  apt: pkg={{ item }} state=latest
  with_items: "{{ php_packages_to_install }}"

- include: configure.yml