---
- hosts: webservers

  vars:
    name: app.tar.gz
    build_folder_name: "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"

  tasks:
    - name: Deploy | Create
      local_action: command chdir={{ playbook_dir }}/../ tar -zcvf ansible/builds/{{ name }} public/

    - name: Remove the folder
      file: path=/jenkins/live state=absent

    - name: Create the folder
      file: path=/jenkins/live state=directory

    - name: Copy and unarchive current build artifact
      unarchive: src=builds/{{ name }} dest=/jenkins/live owner=www-data group=www-data

    - name: Restart nginx
      raw: service nginx restart

    - debug: msg="Deployed to {{ ansible_default_ipv4.address }}"