---
- hosts: dev01
  vars_files:
    - vars/all.yml

  roles:
    - nginx
    - php
    - geerlingguy.composer

  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
      with_items: "{{ packages }}"

    - name: Install phpfpm
      apt:
        name: php7.0-fpm

  post_tasks:
    - name: Ensure github.com is a known host
      lineinfile:
        dest: /root/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"