---
- hosts: webservers
  vars_files:
    - vars/all.yml

  roles:
    - php
    - geerlingguy.composer
    - server

  post_tasks:
    - name: Create directory for apps
      file: path=/root/apps state=directory mode=0755