---
- hosts: jenkins-slave
  vars_files:
    - vars/all.yml

  roles:
    - php
    - geerlingguy.composer

  tasks:
    - name: Install packages
      apt:
        name: {{ item }}
      with_items: "{{ packages }}"

  post_tasks:
    - name: Ensure github.com is a known host
      lineinfile:
        dest: /root/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"