---
- hosts: localhost
  connection: local

  tasks:
    - name: List droplets by tag
      uri:
        url: https://api.digitalocean.com/v2/droplets?tag_name=jenkins-slave
        method: GET
        body:
            type: "convert"
        body_format: json
        HEADER_Content-Type: "application/json"
        HEADER_Authorization: "Bearer d2db2e50d23937890ac3c82b351a3d5dddcfe6f1c9b1068aa3df427a9ea82755"
        status_code: 200
      register: droplet

    - debug: msg="Droplet id {{ droplet['json']['droplets'][0]['id'] }}"

    - name: List snapshots by droplet id
      uri:
        url: https://api.digitalocean.com/v2/droplets/{{ droplet['json']['droplets'][0]['id'] }}/snapshots?page=1&per_page=1
        method: GET
        HEADER_Content-Type: "application/json"
        HEADER_Authorization: "Bearer d2db2e50d23937890ac3c82b351a3d5dddcfe6f1c9b1068aa3df427a9ea82755"
        status_code: 200
      register: droplet_snapshots

    - name: Remove all snapshots
      uri:
        url: https://api.digitalocean.com/v2/snapshots/{{ item.id }}
        method: DELETE
        HEADER_Content-Type: "application/json"
        HEADER_Authorization: "Bearer d2db2e50d23937890ac3c82b351a3d5dddcfe6f1c9b1068aa3df427a9ea82755"
        status_code: 204
      when: droplet_snapshots['json']['snapshots'] > 1
      with_items: "{{ droplet_snapshots['json']['snapshots'] }}"

    - name: Create snapshot
      uri:
        url: https://api.digitalocean.com/v2/droplets/{{ droplet['json']['droplets'][0]['id'] }}/actions
        method: POST
        body:
            type: "snapshot"
            name: "jenkinsSlave"
        body_format: json
        HEADER_Content-Type: "application/json"
        HEADER_Authorization: "Bearer d2db2e50d23937890ac3c82b351a3d5dddcfe6f1c9b1068aa3df427a9ea82755"
        status_code: 201
      register: droplet_snapshot

    - debug: msg="Jenkins slave snapshot id {{ droplet_snapshot['json']['action']['id'] }} and status {{ droplet_snapshot['json']['action']['status'] }}"